// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Misaka.Sample.Web.Application;

namespace Misaka.Sample.Web.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20190713220801_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Misaka.EntityFrameworkCore.MessageConsumed", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ConsumeTime");

                    b.Property<string>("MessageBody");

                    b.Property<string>("Topic");

                    b.HasKey("Id");

                    b.ToTable("_msg_consumed");
                });

            modelBuilder.Entity("Misaka.EntityFrameworkCore.MessageHandle", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConsumeId");

                    b.Property<string>("Exception");

                    b.Property<string>("HandleName");

                    b.HasKey("Id");

                    b.HasIndex("ConsumeId");

                    b.ToTable("_msg_handles");
                });

            modelBuilder.Entity("Misaka.EntityFrameworkCore.MessagePublished", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MessageBody");

                    b.Property<string>("Producer");

                    b.Property<string>("PublishError");

                    b.Property<DateTime>("PublishTime");

                    b.Property<string>("Topic");

                    b.HasKey("Id");

                    b.ToTable("_msg_published");
                });

            modelBuilder.Entity("Misaka.EntityFrameworkCore.MessageHandle", b =>
                {
                    b.HasOne("Misaka.EntityFrameworkCore.MessageConsumed")
                        .WithMany()
                        .HasForeignKey("ConsumeId");
                });
#pragma warning restore 612, 618
        }
    }
}
